name: 'Build latex file'
description: 'Build latex file to pdf'
inputs:
  tex:
    description: 'Latex file to build'
    required: true
  name:
    description: 'Output pdf file name'
    required: false
outputs:
  pdf:
    description: 'Built pdf file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.root_file }}
